development:
  adapter: postgresql
  encoding: utf8
  database: postgres
  pool: 5
  username: postgres
  password: m1710spxD
  host: localhost

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: project_test
  pool: 5
  username: 
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: project_production
  pool: 5
  username: 
  password:

cucumber:
  <<: *TEST
